### ISSUE TITLE
Driver baseUrl parameter not being used and throwing error

### ISSUE THREAD

**Issue by lsjroberts** [Adezandee/cucumber-mink#22]
It seems the `baseUrl` parameter isn't being used by the `root` method in [step_definitions/ext/navigation.js](https://github.com/Adezandee/cucumber-mink/blob/master/lib/step_definitions/ext/navigation.js#L14-L21).

I am on version `1.0.0` and have the following configuration:

```js
var mink = require('cucumber-mink');

var parameters = {
  driver: {
    baseUrl: 'https://example.local/',
    port: 3001,
    desiredCapabilities: {
      browserName: 'phantomjs'
    }
  }
};

module.exports = function () {
  mink.init(this, parameters);
};
```

Using the step `And I am on the homepage` I get:

```
Error: Please provide a base url to use root functions !
    at [object Object].exports.root (/path/to/node_modules/cucumber-mink/lib/step_definitions/ext/navigation.js:17:14)
    at Object.<anonymous> (/path/to/features/support/scenarios/auth.js:7:5)
    at process._tickDomainCallback (node.js:381:11)
```

And using `And I am on "/"` I get:

```
TypeError: Parameter 'url' must be a string, not object
    at Url.parse (url.js:110:11)
    at urlParse (url.js:104:5)
    at Object.urlResolve [as resolve] (url.js:437:10)
    at [object Object].exports.browse (/path/to/node_modules/cucumber-mink/lib/step_definitions/ext/navigation.js:24:23)
    at Object.<anonymous> (/path/to/features/support/scenarios/auth.js:7:5)
    at process._tickDomainCallback (node.js:381:11)
```

Should I not pass it in as a paramter but set it using the a `baseUrl()` method in [step_definitions/ext/utility.js](https://github.com/Adezandee/cucumber-mink/blob/master/lib/step_definitions/ext/utility.js#L21-L25)? At what point should that be called?

**Comment by Adezandee** [comment]
Hi, thanks for your feedback !
Indeed, the parameter isn't correctly handled, i'll post a fix right away

I never came across this because i usually start by test with

``` gherkin
  Background:
    Given I browse "http://localhost:3000"
```

witch basically do `this.driver.baseUrl = "http://localhost:3000";`

anyway, thx for your issue :)

**Comment by Adezandee** [comment]
Dunno why it was automatically closed... anyway, i published a patch : https://github.com/Adezandee/cucumber-mink/releases/tag/v1.0.1

**Comment by lsjroberts** [comment]
Thank you for the quick response and fix! I've updated and it reaches the homepage correctly now.

It does seem to never get to the next step though, I'll have a look into that. If it's not my fault I'll post up a new issue. Thanks :)
