### ISSUE TITLE
Couldn't connect to selenium server

### ISSUE THREAD

**Issue by ShadeLotus** [Adezandee/cucumber-mink#30]
Running cucumber-mink I get:

```
lotus@Infinity:~/code/soundboard-app$ cucumber-mink 
Cucumber-mink v1.0.2. Launching phantomjs on port 8910...

/usr/local/lib/node_modules/cucumber-mink/node_modules/webdriverio/node_modules/q/q.js:141
                throw e;
                      ^
Error: Couldn't connect to selenium server
  at new ErrorHandler.RuntimeError (/usr/local/lib/node_modules/cucumber-mink/node_modules/webdriverio/lib/utils/ErrorHandler.js:92:12)
  at RequestHandler.<anonymous> (/usr/local/lib/node_modules/cucumber-mink/node_modules/webdriverio/lib/utils/RequestHandler.js:147:25)
  at self.callback (/usr/local/lib/node_modules/cucumber-mink/node_modules/webdriverio/node_modules/request/request.js:373:22)
  at Request.emit (events.js:107:17)
  at Request.onRequestError (/usr/local/lib/node_modules/cucumber-mink/node_modules/webdriverio/node_modules/request/request.js:971:8)
  at ClientRequest.emit (events.js:107:17)
  at Socket.socketErrorListener (_http_client.js:271:9)
  at Socket.emit (events.js:107:17)
  at net.js:459:14
  at process._tickDomainCallback (node.js:381:11)

```

**Comment by Adezandee** [comment]
Hi @ShadeLotus,
Maybe didn't launched phantomjs properly, try `$ phantomjs -w` in another terminal

**Comment by ShadeLotus** [comment]
This in the phantomjs terminal:

```
lotus@Infinity:~$ phantomjs -w
PhantomJS is launching GhostDriver...
[INFO  - 2015-09-23T18:05:12.821Z] GhostDriver - Main - running on port 8910
[INFO  - 2015-09-23T18:05:23.373Z] Session [a901cfb0-621d-11e5-8a04-2f23f438e993] - CONSTRUCTOR - Desired Capabilities: {"browserName":"phantomjs","version":"","javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"platform":"ANY","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"3.2.4","name":"webdriverio"}}
[INFO  - 2015-09-23T18:05:23.373Z] Session [a901cfb0-621d-11e5-8a04-2f23f438e993] - CONSTRUCTOR - Negotiated Capabilities: {"browserName":"phantomjs","version":"1.9.0","driverName":"ghostdriver","driverVersion":"1.0.3","platform":"linux-unknown-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2015-09-23T18:05:23.373Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: a901cfb0-621d-11e5-8a04-2f23f438e993
```

this in the cucumber-mink terminal

```
lotus@Infinity:~/code/soundboard-app$ cucumber-mink
Cucumber-mink v1.0.2. Launching phantomjs on port 8910...

/usr/local/lib/node_modules/cucumber-mink/node_modules/webdriverio/node_modules/q/q.js:141
                throw e;
                      ^
Error: Couldn't connect to selenium server
  at new ErrorHandler.RuntimeError (/usr/local/lib/node_modules/cucumber-mink/node_modules/webdriverio/lib/utils/ErrorHandler.js:92:12)
  at RequestHandler.<anonymous> (/usr/local/lib/node_modules/cucumber-mink/node_modules/webdriverio/lib/utils/RequestHandler.js:147:25)
  at self.callback (/usr/local/lib/node_modules/cucumber-mink/node_modules/webdriverio/node_modules/request/request.js:373:22)
  at Request.emit (events.js:107:17)
  at Request.onRequestError (/usr/local/lib/node_modules/cucumber-mink/node_modules/webdriverio/node_modules/request/request.js:971:8)
  at ClientRequest.emit (events.js:107:17)
  at Socket.socketErrorListener (_http_client.js:271:9)
  at Socket.emit (events.js:107:17)
  at net.js:950:16
  at process._tickDomainCallback (node.js:381:11)

```

**Comment by ShadeLotus** [comment]
$ node --version
v0.12.4
$ phantomjs --version
1.9.0

**Comment by ShadeLotus** [comment]
Is this simply a problem in webdriverio or is it in how we use it?

**Comment by Adezandee** [comment]
I don't know for your specific version of phantomjs, i usually use 1.9.7+

**Comment by ShadeLotus** [comment]
Hellz yeah, upgrading to phantomjs 1.9.8 caused good things to happen.

Thank you :)
