### ISSUE TITLE
Clarify the doc, add working exemples ?

### ISSUE THREAD

**Issue by fgiroud** [Adezandee/cucumber-mink#324]
Hi, thanks for this package, I believe it has a huge potential, beeing a fan of behat/mink myself.
However as an advanced beginner in javascript I struggle to make it work.

Could you add working exemples ?

## Problem 1 : Local or global install ?
According to this issue : https://github.com/cucumber/cucumber-js/issues/908, cucumber needs to be installed locally only
When I run 
```
npm install -g cucumber && npm install -g cucumber-mink
cucumber-mink
```
I got : 
```
Error: Cannot find module 'cucumber' from '/Volumes/data/projects/test-cucumber-mink'
...
```

## Problem 2 - how to use support files ?
Do you have a working exemple on how to use support files ?
It took me a long time to understand that [the exemples in the code repository](https://github.com/Adezandee/cucumber-mink/tree/master/examples)  are written in es-6, finally I used the code described [here](http://cucumber-mink.js.org/), and finally succeed in opening a browser with selenium (protractor webdriver-manager)
Also I had to dig into the issues to find this: `./node_modules/.bin/cucumber-mink --inject=false -- -r features/support/mink.js`

## Problem 3 
Maybe not related to cucumber-mink, but I tried all the browsers, including phantom js, and they all return a blank page, whathever I do
```
Failures:

1) Scenario: Go on post 1 # features/test.feature:3
   ✔ When I browse "http://cucumber-mink.js.org/" # node_modules/cucumber-mink/src/mink.js:115
   ✔ Then I wait 3 seconds # node_modules/cucumber-mink/src/mink.js:115
   ✖ Then I should see "In order to run ours test suite" # node_modules/cucumber-mink/src/mink.js:115
       AssertionError: expected '<html><head></head><body></body></html>' to include 'In order to run ours test suite'
           at Object.driver.html.then (/Volumes/data/projects/test-cucumber-mink/node_modules/cucumber-mink/src/step_definitions/assert_dom.js:13:21)
           at Object.exec (/Volumes/data/projects/test-cucumber-mink/node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
           at Object.resolve (/Volumes/data/projects/test-cucumber-mink/node_modules/webdriverio/build/lib/webdriverio.js:189:29)
           at /Volumes/data/projects/test-cucumber-mink/node_modules/webdriverio/build/lib/webdriverio.js:538:32
           at _fulfilled (/Volumes/data/projects/test-cucumber-mink/node_modules/q/q.js:854:54)
           at self.promiseDispatch.done (/Volumes/data/projects/test-cucumber-mink/node_modules/q/q.js:883:30)
           at Promise.promise.promiseDispatch (/Volumes/data/projects/test-cucumber-mink/node_modules/q/q.js:816:13)
           at /Volumes/data/projects/test-cucumber-mink/node_modules/q/q.js:624:44
           at runSingle (/Volumes/data/projects/test-cucumber-mink/node_modules/q/q.js:137:13)
           at flush (/Volumes/data/projects/test-cucumber-mink/node_modules/q/q.js:125:13)
           at _combinedTickCallback (internal/process/next_tick.js:67:7)
           at process._tickDomainCallback (internal/process/next_tick.js:122:9)
   - Then I take a screenshot # node_modules/cucumber-mink/src/mink.js:115
   ✖ After # node_modules/cucumber-mink/src/mink.js:192
       TypeError: event.isFailed is not a function
           at World.cucumber.After (/Volumes/data/projects/test-cucumber-mink/node_modules/cucumber-mink/src/mink.js:193:20)
           at Function.<anonymous> (/Volumes/data/projects/test-cucumber-mink/node_modules/cucumber/lib/user_code_runner.js:59:25)
           at next (native)
           at tryCatcher (/Volumes/data/projects/test-cucumber-mink/node_modules/cucumber/node_modules/bluebird/js/release/util.js:16:23)
           at PromiseSpawn._promiseFulfilled (/Volumes/data/projects/test-cucumber-mink/node_modules/cucumber/node_modules/bluebird/js/release/generators.js:97:49)
           at Function.<anonymous> (/Volumes/data/projects/test-cucumber-mink/node_modules/cucumber/node_modules/bluebird/js/release/generators.js:201:15)
           at Function.run (/Volumes/data/projects/test-cucumber-mink/node_modules/cucumber/lib/user_code_runner.js:120:22)
           at Object.<anonymous> (/Volumes/data/projects/test-cucumber-mink/node_modules/cucumber/lib/runtime/step_runner.js:40:53)
           at next (native)
           at tryCatcher (/Volumes/data/projects/test-cucumber-mink/node_modules/cucumber/node_modules/bluebird/js/release/util.js:16:23)
           at PromiseSpawn._promiseFulfilled (/Volumes/data/projects/test-cucumber-mink/node_modules/cucumber/node_modules/bluebird/js/release/generators.js:97:49)
           at Async._drainQueue (/Volumes/data/projects/test-cucumber-mink/node_modules/cucumber/node_modules/bluebird/js/release/async.js:138:12)
           at Async._drainQueues (/Volumes/data/projects/test-cucumber-mink/node_modules/cucumber/node_modules/bluebird/js/release/async.js:143:10)
           at Immediate.Async.drainQueues (/Volumes/data/projects/test-cucumber-mink/node_modules/cucumber/node_modules/bluebird/js/release/async.js:17:14)
           at runCallback (timers.js:574:20)
           at tryOnImmediate (timers.js:554:5)
           at processImmediate [as _immediateCallback] (timers.js:533:5)
``` 

Thank you very much

**Comment by Adezandee** [comment]
Done, the documentation contains a step by step guide now.
