### ISSUE TITLE
function timeouts when following links

### ISSUE THREAD

**Issue by dareenzo** [Adezandee/cucumber-mink#331]
Hello,

I've been playing with this trying to get an existing app tested. Right off the bat, I get an error when I try to follow a link as seen below.  Any pointers as to what might be the reason for this to fail?

```
[17:04:41] Starting 'cucumber'...
.F-

Failures:

1) Scenario: search with valid query shows results # features/demo.feature:6
   ✔ Given I am on the homepage # node_modules/cucumber-mink/src/mink.js:21
   ✖ When I follow "Sobre" # node_modules/cucumber-mink/src/mink.js:21
       Error: function timed out, ensure the promise resolves within 5000 milliseconds
           at Timeout._onTimeout (/Users/paulo/Projects/UX/biscate/biscate.co.mz/node_modules/cucumber/lib/user_code_runner.js:93:22)
           at ontimeout (timers.js:458:11)
           at tryOnTimeout (timers.js:296:5)
           at Timer.listOnTimeout (timers.js:259:5)
   - Then I should see "Maputo" # node_modules/cucumber-mink/src/mink.js:21

1 scenario (1 failed)
3 steps (1 failed, 1 skipped, 1 passed)
0m09.441s
[17:05:17] 'cucumber' errored after 36 s
[17:05:17] Error in plugin "gulp-shell"
Message:
    Command `./node_modules/.bin/cucumber-js` failed with exit code 1
```

Thanks

**Comment by rrehbein** [comment]
Cucumber's setDefaultTimeout can be used.

```js
cucumber.setDefaultTimeout(30 * 1000);
```

**Comment by dareenzo** [comment]
Thanks
